"use client";

import {
    SiHtml5,
    SiCss,
    SiTypescript,
    SiReact,
    SiNextdotjs,
    SiVuedotjs,
    SiSvelte,
    SiTailwindcss,
    SiJavascript,
    SiPhp,
    SiDotnet,
    SiExpress,
    SiLaravel,
    SiMysql,
    SiMongodb,
    SiFigma,
    SiDocker,
    SiGit,
} from "react-icons/si";

import SkillBubble from "./SkillBubble";
import { FaPlug, FaCode, FaPaintBrush } from "react-icons/fa";

const skills = [
    {
        name: "React",
        icon: SiReact,
        size: "xl" as const,
        x: "40%",
        y: "37%",
        delay: 0,
        duration: 6,
        rotation: -2,
    },
    {
        name: "Vue.js",
        icon: SiVuedotjs,
        size: "xl" as const,
        x: "57%",
        y: "37%",
        delay: 1,
        duration: 6.5,
        rotation: 2,
    },
    {
        name: "HTML",
        icon: SiHtml5,
        size: "xl" as const,
        x: "18%",
        y: "25%",
        delay: 0.6,
        duration: 7,
        rotation: -3,
    },
    {
        name: "CSS",
        icon: SiCss,
        size: "xl" as const,
        x: "73%",
        y: "25%",
        delay: 1.4,
        duration: 6.2,
        rotation: 3,
    },
    {
        name: "Next.js",
        icon: SiNextdotjs,
        size: "lg" as const,
        x: "34%",
        y: "13%",
        delay: 0.3,
        duration: 6,
        rotation: -2,
    },
    {
        name: "TypeScript",
        icon: SiTypescript,
        size: "lg" as const,
        x: "56%",
        y: "12%",
        delay: 1.2,
        duration: 7,
        rotation: 2,
    },
    {
        name: "Tailwind CSS",
        icon: SiTailwindcss,
        size: "lg" as const,
        x: "8%",
        y: "45%",
        delay: 0.8,
        duration: 5.5,
        rotation: -2,
    },
    {
        name: "JavaScript",
        icon: SiJavascript,
        size: "lg" as const,
        x: "76%",
        y: "47%",
        delay: 1.8,
        duration: 6.5,
        rotation: 2,
    },
    {
        name: "Svelte",
        icon: SiSvelte,
        size: "lg" as const,
        x: "23%",
        y: "55%",
        delay: 1.5,
        duration: 5.8,
        rotation: 3,
    },
    {
        name: "Figma",
        icon: SiFigma,
        size: "lg" as const,
        x: "72%",
        y: "62%",
        delay: 0.5,
        duration: 6.8,
        rotation: -3,
    },
    {
        name: "Photoshop",
        icon: FaPaintBrush,
        size: "lg" as const,
        x: "10%",
        y: "68%",
        delay: 1.1,
        duration: 6,
        rotation: 2,
    },
    {
        name: "PHP",
        icon: SiPhp,
        size: "md" as const,
        x: "3%",
        y: "35%",
        delay: 2,
        duration: 6.5,
        rotation: 2,
    },
    {
        name: "Laravel",
        icon: SiLaravel,
        size: "md" as const,
        x: "29%",
        y: "72%",
        delay: 0.2,
        duration: 5.5,
        rotation: -2,
    },
    {
        name: "MySQL",
        icon: SiMysql,
        size: "md" as const,
        x: "46%",
        y: "72%",
        delay: 1.5,
        duration: 6,
        rotation: 2,
    },
    {
        name: "SQL",
        icon: SiMysql,
        size: "md" as const,
        x: "58%",
        y: "84%",
        delay: 0.7,
        duration: 6.5,
        rotation: -2,
    },
    {
        name: "Git",
        icon: SiGit,
        size: "md" as const,
        x: "70%",
        y: "79%",
        delay: 1.3,
        duration: 5.8,
        rotation: 3,
    },
    {
        name: "API REST",
        icon: FaPlug,
        size: "md" as const,
        x: "87%",
        y: "43%",
        delay: 0.9,
        duration: 6.2,
        rotation: -2,
    },
    {
        name: "VS Code",
        icon: FaCode,
        size: "md" as const,
        x: "17%",
        y: "86%",
        delay: 1.7,
        duration: 7,
        rotation: 2,
    },
    {
        name: ".NET",
        icon: SiDotnet,
        size: "sm" as const,
        x: "84%",
        y: "18%",
        delay: 2,
        duration: 6,
        rotation: 3,
    },
    {
        name: "Express.js",
        icon: SiExpress,
        size: "sm" as const,
        x: "89%",
        y: "58%",
        delay: 1.4,
        duration: 5.5,
        rotation: -3,
    },
    {
        name: "MongoDB",
        icon: SiMongodb,
        size: "sm" as const,
        x: "8%",
        y: "84%",
        delay: 0.5,
        duration: 6.5,
        rotation: 2,
    },
    {
        name: "Docker",
        icon: SiDocker,
        size: "sm" as const,
        x: "80%",
        y: "84%",
        delay: 1.8,
        duration: 7,
        rotation: -2,
    },
    {
        name: "PhpStorm",
        icon: FaCode,
        size: "md" as const,
        x: "38%",
        y: "88%",
        delay: 1.1,
        duration: 6.3,
        rotation: -2,
    },
];

export default function SkillsCloud() {
    return (
        <div className="relative mx-auto h-150 w-full overflow-hidden md:h-210">
            {skills.map((skill) => (
                <SkillBubble
                    key={skill.name}
                    {...skill}
                />
            ))}
        </div>
    );
}