"use client";

import {
    SiHtml5,
    SiCss,
    SiTypescript,
    SiReact,
    SiNextdotjs,
    SiVuedotjs,
    SiSvelte,
    SiTailwindcss,
    SiPhp,
    SiDotnet,
    SiExpress,
    SiMysql,
    SiMongodb,
    SiFigma,
    SiDocker,
    SiGit,
} from "react-icons/si";

import { FaPlug, FaCode, FaPaintBrush } from "react-icons/fa";
import SkillBubble from "./SkillBubble";

const skills = [
    {
        name: "React",
        icon: SiReact,
        size: "xl" as const,
        x: "37%",
        y: "38%",
        delay: 0,
        duration: 6,
        rotation: -2,
    },
    {
        name: "Vue.js",
        icon: SiVuedotjs,
        size: "xl" as const,
        x: "57%",
        y: "38%",
        delay: 1,
        duration: 6.5,
        rotation: 2,
    },
    {
        name: "HTML",
        icon: SiHtml5,
        size: "xl" as const,
        x: "12%",
        y: "23%",
        delay: 0.6,
        duration: 7,
        rotation: -3,
    },
    {
        name: "CSS",
        icon: SiCss,
        size: "xl" as const,
        x: "73%",
        y: "23%",
        delay: 1.4,
        duration: 6.2,
        rotation: 3,
    },
    {
        name: "Next.js",
        icon: SiNextdotjs,
        size: "lg" as const,
        x: "30%",
        y: "10%",
        delay: 0.3,
        duration: 6,
        rotation: -2,
    },
    {
        name: "TypeScript",
        icon: SiTypescript,
        size: "lg" as const,
        x: "53%",
        y: "10%",
        delay: 1.2,
        duration: 7,
        rotation: 2,
    },
    {
        name: "Tailwind CSS",
        icon: SiTailwindcss,
        size: "lg" as const,
        x: "5%",
        y: "43%",
        delay: 0.8,
        duration: 5.5,
        rotation: -2,
    },
    {
        name: "Svelte",
        icon: SiSvelte,
        size: "lg" as const,
        x: "19%",
        y: "55%",
        delay: 1.5,
        duration: 5.8,
        rotation: 3,
    },
    {
        name: "Figma",
        icon: SiFigma,
        size: "lg" as const,
        x: "72%",
        y: "58%",
        delay: 0.5,
        duration: 6.8,
        rotation: -3,
    },
    {
        name: "Photoshop",
        icon: FaPaintBrush,
        size: "lg" as const,
        x: "7%",
        y: "66%",
        delay: 1.1,
        duration: 6,
        rotation: 2,
    },
    {
        name: "PHP",
        icon: SiPhp,
        size: "md" as const,
        x: "2%",
        y: "34%",
        delay: 2,
        duration: 6.5,
        rotation: 2,
    },
    {
        name: "MySQL",
        icon: SiMysql,
        size: "md" as const,
        x: "42%",
        y: "70%",
        delay: 1.5,
        duration: 6,
        rotation: 2,
    },
    {
        name: "API REST",
        icon: FaPlug,
        size: "md" as const,
        x: "87%",
        y: "40%",
        delay: 0.9,
        duration: 6.2,
        rotation: -2,
    },
    {
        name: "Git",
        icon: SiGit,
        size: "md" as const,
        x: "67%",
        y: "76%",
        delay: 1.3,
        duration: 5.8,
        rotation: 3,
    },
    {
        name: "VS Code",
        icon: FaCode,
        size: "md" as const,
        x: "15%",
        y: "82%",
        delay: 1.7,
        duration: 7,
        rotation: 2,
    },
    {
        name: "PhpStorm",
        icon: FaCode,
        size: "sm" as const,
        x: "38%",
        y: "87%",
        delay: 1.1,
        duration: 6.3,
        rotation: -2,
    },
    {
        name: ".NET",
        icon: SiDotnet,
        size: "sm" as const,
        x: "84%",
        y: "17%",
        delay: 2,
        duration: 6,
        rotation: 3,
    },
    {
        name: "Express.js",
        icon: SiExpress,
        size: "sm" as const,
        x: "88%",
        y: "56%",
        delay: 1.4,
        duration: 5.5,
        rotation: -3,
    },
    {
        name: "MongoDB",
        icon: SiMongodb,
        size: "sm" as const,
        x: "7%",
        y: "82%",
        delay: 0.5,
        duration: 6.5,
        rotation: 2,
    },
    {
        name: "Docker",
        icon: SiDocker,
        size: "sm" as const,
        x: "80%",
        y: "82%",
        delay: 1.8,
        duration: 7,
        rotation: -2,
    },
];

export default function SkillsCloud() {
    return (
        <div className="relative mx-auto h-180 w-full overflow-hidden sm:h-195 md:h-210">
            {skills.map((skill) => (
                <SkillBubble
                    key={skill.name}
                    {...skill}
                />
            ))}
        </div>
    );
}